version: '3.8'

services:
  agents-n8n:
    image: n8nio/n8n:latest
    container_name: agents-n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - agents_n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
      - ./n8n/credentials:/home/node/.n8n/credentials
    depends_on:
      - agents-postgres
      - agents-redis
      - agents-qdrant
    restart: unless-stopped
    networks:
      - default

  agents-postgres:
    image: postgres:15-alpine
    container_name: agents-postgres
    env_file:
      - .env
    volumes:
      - agents_postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - default

  agents-redis:
    image: redis:7-alpine
    container_name: agents-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - agents_redis_data:/data
    restart: unless-stopped
    networks:
      - default

  agents-qdrant:
    image: qdrant/qdrant:latest
    container_name: agents-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    volumes:
      - agents_qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - default

volumes:
  agents_n8n_data:
    driver: local
  agents_postgres_data:
    driver: local
  agents_redis_data:
    driver: local
  agents_qdrant_data:
    driver: local

networks:
  default:
    external: true
    name: firehose_nginx